// 'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Components/navbar.js'
import Footer from './Components/footer.js'
import { CacheProvider } from '@chakra-ui/next-js'
import { ChakraProvider } from '@chakra-ui/react'
import { Providers } from './providers'
// import { BrowserRouter as Router, Route, Switch } from 'react-router-dom'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IKEA',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
   
      <html lang="en">
        <body>
          <Navbar />
          
          <Providers>{children}</Providers>
        <Footer />
        </body>
      </html>
   
  )
}
